import type { DesignTemplate, CanvasBackground } from './types';

const solidBg = (color: string): CanvasBackground => ({
  type: 'color', color, gradientStart: '#6366f1', gradientEnd: '#8b5cf6', gradientAngle: 135, imageFit: 'cover',
});

const gradBg = (start: string, end: string, angle = 135): CanvasBackground => ({
  type: 'gradient', color: start, gradientStart: start, gradientEnd: end, gradientAngle: angle, imageFit: 'cover',
});

export const PLATFORM_PRESETS = {
  instagram: { label: 'Instagram', icon: '📸', primaryColor: '#E1306C' },
  facebook:  { label: 'Facebook',  icon: '👥', primaryColor: '#1877F2' },
  twitter:   { label: 'Twitter/X', icon: '🐦', primaryColor: '#1DA1F2' },
  linkedin:  { label: 'LinkedIn',  icon: '💼', primaryColor: '#0A66C2' },
  tiktok:    { label: 'TikTok',    icon: '🎵', primaryColor: '#FF0050' },
  youtube:   { label: 'YouTube',   icon: '▶️', primaryColor: '#FF0000' },
};

export const RATIO_SIZES: Record<string, { width: number; height: number }> = {
  '1:1':  { width: 540, height: 540 },
  '9:16': { width: 405, height: 720 },
  '16:9': { width: 720, height: 405 },
  '4:5':  { width: 540, height: 675 },
  '3:2':  { width: 540, height: 360 },
};

export const FONT_FAMILIES = [
  'Inter', 'Arial', 'Georgia', 'Helvetica', 'Times New Roman', 'Verdana',
  'Trebuchet MS', 'Impact', 'Comic Sans MS', 'Courier New',
];

export const EMOJI_STICKERS = [
  '🔥', '⭐', '💯', '🎉', '✨', '💪', '❤️', '🚀', '💡', '🏆',
  '📈', '💰', '🌟', '👑', '🎯', '⚡', '🌈', '💎', '🦋', '🌸',
  '😍', '🙌', '👏', '🤩', '🥳', '😎', '🤑', '💥', '🎊', '🎁',
  '✅', '❌', '⚠️', '🔔', '📢', '💬', '🗣️', '📌', '🔑', '🎨',
];

export const TEMPLATES: DesignTemplate[] = [
  /* ── MOTIVATIONAL ── */
  {
    id: 'mot-1', name: 'Bold Motivation', category: 'Motivational', platform: 'all',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#6366f1,#a855f7',
    tags: ['motivation', 'quote', 'bold'],
    background: gradBg('#6366f1', '#a855f7'),
    elements: [
      { type: 'text', x: 60, y: 200, width: 420, height: 80, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: 'BELIEVE IN YOURSELF', fontSize: 38, fontFamily: 'Impact', color: '#ffffff', fontWeight: '700', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.2, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 80, y: 300, width: 380, height: 50, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'You are stronger than you think', fontSize: 20, fontFamily: 'Inter', color: 'rgba(255,255,255,0.85)', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.5, letterSpacing: 1, textDecoration: 'none' } },
      { type: 'shape', x: 200, y: 370, width: 140, height: 3, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: 'rgba(255,255,255,0.5)', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
    ],
  },
  {
    id: 'mot-2', name: 'Dark Fire', category: 'Motivational', platform: 'all',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#1a1a2e,#e94560',
    tags: ['motivation', 'dark', 'fire'],
    background: gradBg('#1a1a2e', '#e94560'),
    elements: [
      { type: 'sticker', x: 220, y: 80, width: 100, height: 100, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'sticker', emoji: '🔥', fontSize: 72 } },
      { type: 'text', x: 60, y: 200, width: 420, height: 100, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'RISE & CONQUER', fontSize: 42, fontFamily: 'Impact', color: '#ffffff', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.2, letterSpacing: 4, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 80, y: 320, width: 380, height: 60, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'Every day is a new opportunity', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.8)', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.5, letterSpacing: 1, textDecoration: 'none' } },
    ],
  },
  {
    id: 'mot-3', name: 'Gold Success', category: 'Motivational', platform: 'instagram',
    aspectRatio: '9:16', canvasWidth: 405, canvasHeight: 720,
    thumbnail: 'gradient:135,#1a1a1a,#c9a227',
    tags: ['success', 'gold', 'luxury'],
    background: gradBg('#1a1a1a', '#c9a227'),
    elements: [
      { type: 'sticker', x: 155, y: 100, width: 95, height: 95, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'sticker', emoji: '👑', fontSize: 68 } },
      { type: 'text', x: 40, y: 240, width: 325, height: 120, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'SUCCESS IS A CHOICE', fontSize: 36, fontFamily: 'Impact', color: '#c9a227', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.2, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 40, y: 380, width: 325, height: 80, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'Make it yours', fontSize: 22, fontFamily: 'Georgia', color: '#ffffff', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.4, letterSpacing: 2, textDecoration: 'none' } },
    ],
  },
  /* ── BUSINESS ── */
  {
    id: 'biz-1', name: 'Professional Blue', category: 'Business', platform: 'linkedin',
    aspectRatio: '16:9', canvasWidth: 720, canvasHeight: 405,
    thumbnail: 'gradient:135,#0A66C2,#1e3a5f',
    tags: ['business', 'professional', 'linkedin'],
    background: gradBg('#0A66C2', '#1e3a5f'),
    elements: [
      { type: 'shape', x: 0, y: 0, width: 8, height: 405, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: '#ffffff', stroke: 'transparent', strokeWidth: 0, opacity: 0.9 } },
      { type: 'text', x: 40, y: 100, width: 640, height: 80, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'Grow Your Business', fontSize: 44, fontFamily: 'Inter', color: '#ffffff', fontWeight: '700', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.2, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 40, y: 200, width: 500, height: 60, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'Strategies that drive results in 2024', fontSize: 20, fontFamily: 'Inter', color: 'rgba(255,255,255,0.85)', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.5, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 40, y: 290, width: 200, height: 50, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: 'Learn More →', fontSize: 18, fontFamily: 'Inter', color: '#ffffff', fontWeight: '600', fontStyle: 'normal', textAlign: 'left', lineHeight: 1, letterSpacing: 1, textDecoration: 'underline', backgroundColor: 'rgba(255,255,255,0.2)', padding: 12, borderRadius: 8 } },
    ],
  },
  {
    id: 'biz-2', name: 'Clean White', category: 'Business', platform: 'all',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'color:#f8fafc',
    tags: ['clean', 'minimal', 'business'],
    background: solidBg('#f8fafc'),
    elements: [
      { type: 'shape', x: 40, y: 40, width: 460, height: 460, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rounded-rect', fill: 'transparent', stroke: '#e2e8f0', strokeWidth: 2, opacity: 1 } },
      { type: 'text', x: 80, y: 140, width: 380, height: 70, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'Your Brand Name', fontSize: 36, fontFamily: 'Inter', color: '#1e293b', fontWeight: '700', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.2, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'shape', x: 200, y: 230, width: 140, height: 3, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: '#6366f1', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      { type: 'text', x: 80, y: 260, width: 380, height: 80, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: 'Your tagline or key message goes here', fontSize: 18, fontFamily: 'Inter', color: '#64748b', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.6, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  {
    id: 'biz-3', name: 'Stats Card', category: 'Business', platform: 'linkedin',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#0f172a,#1e40af',
    tags: ['stats', 'data', 'results'],
    background: gradBg('#0f172a', '#1e40af'),
    elements: [
      { type: 'text', x: 60, y: 60, width: 420, height: 50, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '📊 Q4 Results Are In', fontSize: 24, fontFamily: 'Inter', color: '#93c5fd', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.2, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 100, y: 160, width: 160, height: 80, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: '340%', fontSize: 48, fontFamily: 'Inter', color: '#ffffff', fontWeight: '800', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: -2, textDecoration: 'none' } },
      { type: 'text', x: 100, y: 248, width: 160, height: 30, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'ROI Growth', fontSize: 14, fontFamily: 'Inter', color: '#93c5fd', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 280, y: 160, width: 160, height: 80, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: '12K+', fontSize: 48, fontFamily: 'Inter', color: '#ffffff', fontWeight: '800', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: -2, textDecoration: 'none' } },
      { type: 'text', x: 280, y: 248, width: 160, height: 30, rotation: 0, zIndex: 5, locked: false, visible: true,
        data: { kind: 'text', text: 'New Leads', fontSize: 14, fontFamily: 'Inter', color: '#93c5fd', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 60, y: 360, width: 420, height: 60, rotation: 0, zIndex: 6, locked: false, visible: true,
        data: { kind: 'text', text: 'Helping businesses scale with AI automation', fontSize: 16, fontFamily: 'Inter', color: 'rgba(255,255,255,0.7)', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.5, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  /* ── PRODUCT PROMO ── */
  {
    id: 'promo-1', name: 'Sale Banner', category: 'Promotion', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#dc2626,#9f1239',
    tags: ['sale', 'promo', 'discount'],
    background: gradBg('#dc2626', '#9f1239'),
    elements: [
      { type: 'text', x: 40, y: 80, width: 460, height: 60, rotation: -5, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '🎉 MEGA SALE 🎉', fontSize: 36, fontFamily: 'Impact', color: '#ffd700', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 80, y: 180, width: 380, height: 120, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'UP TO\n70% OFF', fontSize: 64, fontFamily: 'Impact', color: '#ffffff', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.1, letterSpacing: 2, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 100, y: 330, width: 340, height: 40, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'Limited Time Only — Shop Now!', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.9)', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 1, textDecoration: 'none' } },
      { type: 'shape', x: 160, y: 400, width: 220, height: 55, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rounded-rect', fill: '#ffd700', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      { type: 'text', x: 160, y: 415, width: 220, height: 30, rotation: 0, zIndex: 5, locked: false, visible: true,
        data: { kind: 'text', text: 'CLAIM OFFER', fontSize: 18, fontFamily: 'Impact', color: '#9f1239', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 2, textDecoration: 'none', uppercase: true } },
    ],
  },
  {
    id: 'promo-2', name: 'Product Feature', category: 'Promotion', platform: 'instagram',
    aspectRatio: '4:5', canvasWidth: 540, canvasHeight: 675,
    thumbnail: 'gradient:180,#0ea5e9,#0369a1',
    tags: ['product', 'feature', 'launch'],
    background: gradBg('#0ea5e9', '#0369a1', 180),
    elements: [
      { type: 'text', x: 50, y: 60, width: 440, height: 40, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '✨ NEW ARRIVAL', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.8)', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 4, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 50, y: 130, width: 440, height: 100, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'Product Name Here', fontSize: 42, fontFamily: 'Inter', color: '#ffffff', fontWeight: '800', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.2, letterSpacing: -1, textDecoration: 'none' } },
      { type: 'text', x: 60, y: 270, width: 420, height: 80, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'Short product description that highlights the main benefit and value proposition', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.85)', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.5, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 150, y: 420, width: 240, height: 50, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: '$99', fontSize: 48, fontFamily: 'Inter', color: '#ffffff', fontWeight: '800', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: -2, textDecoration: 'none' } },
      { type: 'shape', x: 130, y: 510, width: 280, height: 55, rotation: 0, zIndex: 5, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rounded-rect', fill: '#ffffff', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      { type: 'text', x: 130, y: 525, width: 280, height: 30, rotation: 0, zIndex: 6, locked: false, visible: true,
        data: { kind: 'text', text: 'Shop Now', fontSize: 18, fontFamily: 'Inter', color: '#0369a1', fontWeight: '700', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 1, textDecoration: 'none' } },
    ],
  },
  /* ── SOCIAL / ENGAGEMENT ── */
  {
    id: 'social-1', name: 'Question Card', category: 'Engagement', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#f59e0b,#d97706',
    tags: ['engagement', 'question', 'poll'],
    background: gradBg('#f59e0b', '#d97706'),
    elements: [
      { type: 'sticker', x: 220, y: 60, width: 100, height: 100, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'sticker', emoji: '🤔', fontSize: 72 } },
      { type: 'text', x: 60, y: 190, width: 420, height: 60, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'QUESTION OF THE DAY', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.85)', fontWeight: '700', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 60, y: 270, width: 420, height: 100, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'What would you do with an extra hour each day?', fontSize: 28, fontFamily: 'Inter', color: '#ffffff', fontWeight: '700', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.3, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 100, y: 400, width: 340, height: 40, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: '👇 Comment below!', fontSize: 20, fontFamily: 'Inter', color: '#1a1a1a', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  {
    id: 'social-2', name: 'Tips Card', category: 'Educational', platform: 'instagram',
    aspectRatio: '9:16', canvasWidth: 405, canvasHeight: 720,
    thumbnail: 'gradient:135,#10b981,#059669',
    tags: ['tips', 'educational', 'value'],
    background: gradBg('#10b981', '#059669'),
    elements: [
      { type: 'text', x: 30, y: 60, width: 345, height: 40, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '5 TIPS FOR SUCCESS', fontSize: 22, fontFamily: 'Impact', color: '#ffffff', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'shape', x: 100, y: 115, width: 205, height: 3, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: 'rgba(255,255,255,0.5)', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      ...[
        ['1. Wake up early', 160],
        ['2. Set clear goals', 230],
        ['3. Eliminate distractions', 300],
        ['4. Take breaks', 370],
        ['5. Reflect & improve', 440],
      ].map(([text, y], i) => ({
        type: 'text' as const, x: 30, y: y as number, width: 345, height: 55, rotation: 0, zIndex: 3 + i, locked: false, visible: true,
        data: { kind: 'text' as const, text: text as string, fontSize: 20, fontFamily: 'Inter', color: '#ffffff', fontWeight: '600' as const, fontStyle: 'normal' as const, textAlign: 'left' as const, lineHeight: 1.4, letterSpacing: 0, textDecoration: 'none' as const, uppercase: false },
      })),
      { type: 'text', x: 30, y: 600, width: 345, height: 40, rotation: 0, zIndex: 10, locked: false, visible: true,
        data: { kind: 'text', text: '🌱 Save this for later!', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.8)', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  {
    id: 'social-3', name: 'Before/After', category: 'Testimonial', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:90,#7c3aed,#2563eb',
    tags: ['testimonial', 'results', 'social proof'],
    background: gradBg('#7c3aed', '#2563eb', 90),
    elements: [
      { type: 'shape', x: 30, y: 30, width: 240, height: 480, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rounded-rect', fill: 'rgba(0,0,0,0.3)', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      { type: 'text', x: 30, y: 60, width: 240, height: 40, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'BEFORE', fontSize: 22, fontFamily: 'Impact', color: '#ef4444', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 50, y: 130, width: 200, height: 200, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: '• No leads\n• No strategy\n• No growth\n• Overwhelmed', fontSize: 16, fontFamily: 'Inter', color: '#ffffff', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.8, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'shape', x: 270, y: 30, width: 240, height: 480, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rounded-rect', fill: 'rgba(255,255,255,0.15)', stroke: 'rgba(255,255,255,0.3)', strokeWidth: 1, opacity: 1 } },
      { type: 'text', x: 270, y: 60, width: 240, height: 40, rotation: 0, zIndex: 5, locked: false, visible: true,
        data: { kind: 'text', text: 'AFTER', fontSize: 22, fontFamily: 'Impact', color: '#4ade80', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 3, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 290, y: 130, width: 200, height: 200, rotation: 0, zIndex: 6, locked: false, visible: true,
        data: { kind: 'text', text: '• 10× more leads\n• Clear roadmap\n• 300% growth\n• Confident!', fontSize: 16, fontFamily: 'Inter', color: '#ffffff', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.8, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  /* ── QUOTE / TESTIMONIAL ── */
  {
    id: 'quote-1', name: 'Minimal Quote', category: 'Quote', platform: 'all',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'color:#0f172a',
    tags: ['quote', 'minimal', 'dark'],
    background: solidBg('#0f172a'),
    elements: [
      { type: 'text', x: 60, y: 100, width: 420, height: 60, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '"', fontSize: 120, fontFamily: 'Georgia', color: '#6366f1', fontWeight: '700', fontStyle: 'normal', textAlign: 'left', lineHeight: 1, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 60, y: 180, width: 420, height: 160, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'The secret of getting ahead is getting started.', fontSize: 26, fontFamily: 'Georgia', color: '#f1f5f9', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'left', lineHeight: 1.5, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'shape', x: 60, y: 360, width: 80, height: 3, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: '#6366f1', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      { type: 'text', x: 60, y: 385, width: 300, height: 30, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: '— Mark Twain', fontSize: 16, fontFamily: 'Georgia', color: '#94a3b8', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'left', lineHeight: 1, letterSpacing: 1, textDecoration: 'none' } },
    ],
  },
  {
    id: 'quote-2', name: 'Pink Quote', category: 'Quote', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#fce7f3,#fbcfe8',
    tags: ['quote', 'pink', 'feminine'],
    background: gradBg('#fce7f3', '#fbcfe8'),
    elements: [
      { type: 'text', x: 60, y: 180, width: 420, height: 150, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '"She believed she could, so she did."', fontSize: 28, fontFamily: 'Georgia', color: '#9d174d', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.5, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'sticker', x: 230, y: 80, width: 80, height: 80, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'sticker', emoji: '🌸', fontSize: 56 } },
      { type: 'text', x: 100, y: 360, width: 340, height: 30, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: '✨ You are capable of amazing things', fontSize: 16, fontFamily: 'Inter', color: '#be185d', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 1, textDecoration: 'none' } },
    ],
  },
  /* ── ANNOUNCEMENT ── */
  {
    id: 'ann-1', name: 'Event Launch', category: 'Announcement', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#1e1b4b,#312e81',
    tags: ['event', 'launch', 'announcement'],
    background: gradBg('#1e1b4b', '#312e81'),
    elements: [
      { type: 'sticker', x: 230, y: 50, width: 80, height: 80, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'sticker', emoji: '🚀', fontSize: 56 } },
      { type: 'text', x: 40, y: 160, width: 460, height: 50, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'BIG ANNOUNCEMENT', fontSize: 28, fontFamily: 'Impact', color: '#a5b4fc', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 4, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 40, y: 240, width: 460, height: 100, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'We\'re launching something incredible', fontSize: 30, fontFamily: 'Inter', color: '#ffffff', fontWeight: '700', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.3, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 100, y: 370, width: 340, height: 40, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: 'Stay tuned — June 25, 2024', fontSize: 18, fontFamily: 'Inter', color: '#c7d2fe', fontWeight: '500', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 1, textDecoration: 'none' } },
    ],
  },
  {
    id: 'ann-2', name: 'New Product', category: 'Announcement', platform: 'all',
    aspectRatio: '16:9', canvasWidth: 720, canvasHeight: 405,
    thumbnail: 'gradient:90,#14532d,#22c55e',
    tags: ['product', 'new', 'launch'],
    background: gradBg('#14532d', '#22c55e', 90),
    elements: [
      { type: 'text', x: 60, y: 70, width: 600, height: 50, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '✨ INTRODUCING', fontSize: 20, fontFamily: 'Inter', color: 'rgba(255,255,255,0.8)', fontWeight: '600', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 5, textDecoration: 'none', uppercase: true } },
      { type: 'text', x: 60, y: 140, width: 600, height: 90, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'Your Product Name', fontSize: 52, fontFamily: 'Inter', color: '#ffffff', fontWeight: '800', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.1, letterSpacing: -2, textDecoration: 'none' } },
      { type: 'text', x: 120, y: 260, width: 480, height: 50, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: 'The future of [category] is here. Coming soon.', fontSize: 18, fontFamily: 'Inter', color: 'rgba(255,255,255,0.85)', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1.4, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  /* ── TESTIMONIAL ── */
  {
    id: 'test-1', name: 'Star Review', category: 'Testimonial', platform: 'all',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#fffbeb,#fef3c7',
    tags: ['testimonial', 'review', 'stars'],
    background: gradBg('#fffbeb', '#fef3c7'),
    elements: [
      { type: 'text', x: 100, y: 80, width: 340, height: 50, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '⭐⭐⭐⭐⭐', fontSize: 36, fontFamily: 'Inter', color: '#f59e0b', fontWeight: 'normal', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 2, textDecoration: 'none' } },
      { type: 'text', x: 60, y: 160, width: 420, height: 180, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: '"This is honestly the best service I\'ve ever used. It completely transformed my business in just 30 days!"', fontSize: 22, fontFamily: 'Georgia', color: '#1e293b', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.5, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'shape', x: 200, y: 360, width: 140, height: 3, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: '#f59e0b', stroke: 'transparent', strokeWidth: 0, opacity: 1 } },
      { type: 'text', x: 100, y: 385, width: 340, height: 30, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: '— Sarah M., CEO at TechStartup', fontSize: 16, fontFamily: 'Inter', color: '#64748b', fontWeight: '500', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  /* ── MINIMAL / AESTHETIC ── */
  {
    id: 'aes-1', name: 'Minimalist', category: 'Aesthetic', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'color:#fafaf9',
    tags: ['minimal', 'clean', 'aesthetic'],
    background: solidBg('#fafaf9'),
    elements: [
      { type: 'shape', x: 120, y: 220, width: 300, height: 1, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: '#d4c5a9', stroke: 'transparent', strokeWidth: 0, opacity: 0.6 } },
      { type: 'text', x: 60, y: 240, width: 420, height: 80, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'simplicity is the ultimate sophistication', fontSize: 20, fontFamily: 'Georgia', color: '#5c5c4a', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.6, letterSpacing: 2, textDecoration: 'none' } },
      { type: 'shape', x: 120, y: 340, width: 300, height: 1, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rect', fill: '#d4c5a9', stroke: 'transparent', strokeWidth: 0, opacity: 0.6 } },
    ],
  },
  {
    id: 'aes-2', name: 'Neon Glow', category: 'Aesthetic', platform: 'instagram',
    aspectRatio: '1:1', canvasWidth: 540, canvasHeight: 540,
    thumbnail: 'gradient:135,#0a0a0a,#0a0a0a',
    tags: ['neon', 'dark', 'aesthetic', 'glow'],
    background: solidBg('#0a0a0a'),
    elements: [
      { type: 'text', x: 40, y: 180, width: 460, height: 100, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: 'NEON DREAMS', fontSize: 56, fontFamily: 'Impact', color: '#00ff88', fontWeight: '900', fontStyle: 'normal', textAlign: 'center', lineHeight: 1, letterSpacing: 5, textDecoration: 'none', uppercase: true, textShadow: '0 0 30px #00ff88, 0 0 60px #00ff88' } },
      { type: 'text', x: 80, y: 300, width: 380, height: 50, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'where creativity has no limits', fontSize: 18, fontFamily: 'Inter', color: '#ff0080', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.4, letterSpacing: 3, textDecoration: 'none', textShadow: '0 0 20px #ff0080' } },
    ],
  },
  /* ── YOUTUBE THUMBNAIL ── */
  {
    id: 'yt-1', name: 'YouTube Thumb', category: 'YouTube', platform: 'youtube',
    aspectRatio: '16:9', canvasWidth: 720, canvasHeight: 405,
    thumbnail: 'gradient:135,#ff6b35,#f7c59f',
    tags: ['youtube', 'thumbnail', 'clickbait'],
    background: gradBg('#ff6b35', '#f7c59f'),
    elements: [
      { type: 'text', x: 20, y: 40, width: 440, height: 120, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: 'I TRIED THIS FOR\n30 DAYS...', fontSize: 52, fontFamily: 'Impact', color: '#ffffff', fontWeight: '900', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.1, letterSpacing: 1, textDecoration: 'none', uppercase: true, textShadow: '3px 3px 0 #000' } },
      { type: 'text', x: 20, y: 180, width: 380, height: 50, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: '(the results surprised me)', fontSize: 24, fontFamily: 'Inter', color: '#ffd700', fontWeight: '700', fontStyle: 'normal', textAlign: 'left', lineHeight: 1, letterSpacing: 0, textDecoration: 'none', textShadow: '2px 2px 0 #000' } },
      { type: 'shape', x: 490, y: 20, width: 210, height: 365, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'shape', shapeType: 'rounded-rect', fill: 'rgba(0,0,0,0.3)', stroke: 'transparent', strokeWidth: 0, opacity: 0.6 } },
      { type: 'text', x: 490, y: 160, width: 210, height: 80, rotation: 0, zIndex: 4, locked: false, visible: true,
        data: { kind: 'text', text: 'Your face photo goes here', fontSize: 14, fontFamily: 'Inter', color: 'rgba(255,255,255,0.7)', fontWeight: 'normal', fontStyle: 'italic', textAlign: 'center', lineHeight: 1.4, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
  /* ── TIKTOK ── */
  {
    id: 'tt-1', name: 'TikTok Viral', category: 'TikTok', platform: 'tiktok',
    aspectRatio: '9:16', canvasWidth: 405, canvasHeight: 720,
    thumbnail: 'gradient:135,#010101,#1a0a2e',
    tags: ['tiktok', 'viral', 'trending'],
    background: gradBg('#010101', '#1a0a2e'),
    elements: [
      { type: 'text', x: 20, y: 80, width: 365, height: 60, rotation: 0, zIndex: 1, locked: false, visible: true,
        data: { kind: 'text', text: '🔥 POV:', fontSize: 32, fontFamily: 'Impact', color: '#ffffff', fontWeight: '900', fontStyle: 'normal', textAlign: 'left', lineHeight: 1, letterSpacing: 1, textDecoration: 'none' } },
      { type: 'text', x: 20, y: 160, width: 365, height: 150, rotation: 0, zIndex: 2, locked: false, visible: true,
        data: { kind: 'text', text: 'You finally start your own business at 25', fontSize: 36, fontFamily: 'Impact', color: '#ffffff', fontWeight: '900', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.2, letterSpacing: 0, textDecoration: 'none' } },
      { type: 'text', x: 20, y: 550, width: 365, height: 60, rotation: 0, zIndex: 3, locked: false, visible: true,
        data: { kind: 'text', text: '#entrepreneur #business #fyp', fontSize: 18, fontFamily: 'Inter', color: '#00f2ea', fontWeight: '600', fontStyle: 'normal', textAlign: 'left', lineHeight: 1.4, letterSpacing: 0, textDecoration: 'none' } },
    ],
  },
];

export const TEMPLATE_CATEGORIES = [...new Set(TEMPLATES.map(t => t.category))];
