/* The voice sets the clock.
 *
 * v1 placed the lines on a timeline drawn first, which left the narration
 * waiting for the pictures — silences of two and three seconds between
 * scenes. Here each line is measured and laid end to end, and each scene
 * lasts exactly as long as its own lines. The scenes are then moved into
 * those slots by `place()` in film.js, so a scene's animation stretches or
 * tightens to fit what is being said over it.
 *
 *   node timing.mjs [voDir]   → timing.js (window.NT, window.DURATION) and vo.json
 */
import fs from 'node:fs';

const voDir = process.argv[2] ?? 'vo';
const lines = JSON.parse(fs.readFileSync(new URL('./lines.json', import.meta.url)));

/** Seconds of audio in a PCM WAV, read from its header. */
function wavSeconds(file) {
  const b = fs.readFileSync(file);
  let byteRate = 0, off = 12;
  while (off < b.length - 8) {
    const id = b.toString('ascii', off, off + 4), size = b.readUInt32LE(off + 4);
    if (id === 'fmt ') byteRate = b.readUInt32LE(off + 16);
    if (id === 'data') return size / byteRate;
    off += 8 + size + (size & 1);
  }
  throw new Error(`no data chunk in ${file}`);
}

const GAP_IN = 0.16;   // between two lines of one scene — a breath, not a pause
const GAP_OUT = 0.24;  // between scenes
const LEAD = 0.3;      // the picture arrives just before the voice
const OVERLAP = 0.45;  // scenes cross-fade
const INTRO = { v01: 0.3, v02: 3.4, end: 6.4, next: 6.2 }; // the intro is drawn to fixed beats
const TAIL = 3.2;      // the offer stays up after the last word

const order = [], byScene = {}, vo = [];
let cur = 0;
for (const [id, sc] of lines) {
  const d = wavSeconds(`${voDir}/${id}.wav`);
  let t;
  if (sc === 'intro') t = INTRO[id];
  else if (!byScene[sc]) {
    t = order.length === 1 ? INTRO.next : cur + GAP_OUT;
    byScene[sc] = { a: t - LEAD };
    order.push(sc);
  } else t = cur + GAP_IN;
  if (sc === 'intro' && !byScene.intro) { byScene.intro = { a: 0 }; order.push('intro'); }
  vo.push({ id, t: +t.toFixed(3), d: +d.toFixed(3) });
  cur = t + d;
  byScene[sc].end = cur;
}

const NT = {}, COPY = {};
order.forEach((sc, i) => {
  const next = order[i + 1];
  const a = byScene[sc].a;
  const b = next ? byScene[next].a + OVERLAP : cur + TAIL;
  NT[sc] = [+a.toFixed(3), +(sc === 'intro' ? INTRO.end : b).toFixed(3)];
  COPY[sc] = [+(a + 0.15).toFixed(3), +((next ? byScene[next].a : b) + 0.1).toFixed(3)];
});
const DURATION = +(cur + TAIL).toFixed(2);

fs.writeFileSync(new URL('./timing.js', import.meta.url),
  `/* Generated by timing.mjs from the measured voice lines — do not edit. */\n` +
  `window.NT = ${JSON.stringify(NT)};\nwindow.NC = ${JSON.stringify(COPY)};\nwindow.DURATION = ${DURATION};\n`);
fs.writeFileSync(new URL('./vo.json', import.meta.url), JSON.stringify(vo));
console.log(`${order.length} scenes, ${vo.length} lines, ${DURATION}s`);
for (const sc of order) console.log(sc.padEnd(10), NT[sc].join(' → '), `(${(NT[sc][1] - NT[sc][0]).toFixed(1)}s)`);
